### ISSUE TITLE
Problems with bower installation

### ISSUE THREAD

**Issue by mmerchel** [backbone-api/facebook#5]
I had some problems with the Bower installation. In the bower list was the old url included. I registered the repo now to backbone-api-facebook.

**Comment by tracend** [comment]
I remember @mmerchel you reported this on issue #4 

Ideally the `backbone.api.facebook` should look at this repo but since updating this is not an option of the Bower cli (yet) I'm trying to maintain the gist and push the changes there as well. 

Thanks for taking initiative to find a solution, but I don't feel very comfortable polluting the bower registry with duplicate entries. Would you mind making a request at the relevant [bower issue](https://github.com/bower/bower/issues/120) instead?

**Comment by tracend** [comment]
Thanks again @mmerchel - the bower listing for `backbone.api.facebook` seems to be updated to this repo. 

Closing as addressed.
